name: Docker
on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  traefik-forward-auth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: botpress/gh-actions/build/docker@v2
        with:
          repository: traefik-forward-auth
